# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Comment.create!([
  { :user_id => 1, :note_id => 1, :text => "I moved this to winter crops - I don't think they grow well in the summer.\r\n" },
  { :user_id => 2, :note_id => 3, :text => "Thanks so much - they were delicious!\r\n" },
  { :user_id => 2, :note_id => 6, :text => "Thanks - could you pick up a bag of topsoil? I'll owe you one!"},
  { :user_id => 2, :note_id => 7, :text => "And will it grow in New York?\r\n" }
])



Garden.create!([
  { :name => "Worcester St Community Garden", :location => "Roxbury, MA", :user_id => 1, :zip => nil }
])



GardenMembership.create!([
  { :garden_id => 1, :user_id => 2 }
])



List.create!([
  { :user_id => 1, :garden_id => 1, :name => "Summer Planting", :list_pos => 0 },
  { :user_id => 1, :garden_id => 1, :name => "Winter Crops", :list_pos => 1 },
  { :user_id => 1, :garden_id => 1, :name => "Home Depot Shopping List!", :list_pos => 2 },
  { :user_id => 1, :garden_id => 1, :name => "Halloween Party!", :list_pos => 3 },
  { :user_id => 1, :garden_id => 1, :name => "HELP!", :list_pos => 4 }
])



Note.create!([
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Onions", :note_photo_file_name => "7791743194_78c86a4518_b_-_onions.jpg", :note_photo_content_type => "image/jpeg", :note_photo_file_size => 383802, :note_photo_updated_at => "2013-11-08 16:44:58", :list_id => 2, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => nil, :flag3 => nil, :flag4 => true, :flag5 => true, :assigned_user => nil, :note_pos => 2 },
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Cukes", :note_photo_file_name => nil, :note_photo_content_type => nil, :note_photo_file_size => nil, :note_photo_updated_at => nil, :list_id => 1, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => nil, :flag3 => nil, :flag4 => nil, :flag5 => nil, :assigned_user => nil, :note_pos => 0 },
  { :user_id => 1, :crop_id => nil, :text => "Extra tomatoes - I planted too much. Help yourselves!", :title => "Tomatoes", :note_photo_file_name => "tomatoes.jpg", :note_photo_content_type => "image/jpeg", :note_photo_file_size => 647932, :note_photo_updated_at => "2013-11-08 16:48:43", :list_id => 2, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => nil, :flag3 => true, :flag4 => nil, :flag5 => nil, :assigned_user => nil, :note_pos => 3 },
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Kale", :note_photo_file_name => nil, :note_photo_content_type => nil, :note_photo_file_size => nil, :note_photo_updated_at => nil, :list_id => 2, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => nil, :flag3 => nil, :flag4 => nil, :flag5 => nil, :assigned_user => nil, :note_pos => 0 },
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Let me know if you need anything", :note_photo_file_name => nil, :note_photo_content_type => nil, :note_photo_file_size => nil, :note_photo_updated_at => nil, :list_id => 3, :due_date => "2013-11-10", :completion => nil, :flag1 => nil, :flag2 => true, :flag3 => nil, :flag4 => nil, :flag5 => nil, :assigned_user => 1, :note_pos => 0 },
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Does anyone know what this is?", :note_photo_file_name => "fractal.jpg", :note_photo_content_type => "image/jpeg", :note_photo_file_size => 370373, :note_photo_updated_at => "2013-11-08 16:50:10", :list_id => 1, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => true, :flag3 => nil, :flag4 => nil, :flag5 => nil, :assigned_user => nil, :note_pos => 1 },
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Farmers Market", :note_photo_file_name => "farmers-m.jpg", :note_photo_content_type => "image/jpeg", :note_photo_file_size => 210139, :note_photo_updated_at => "2013-11-08 16:51:06", :list_id => 5, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => nil, :flag3 => nil, :flag4 => nil, :flag5 => nil, :assigned_user => nil, :note_pos => 0 },
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Garden Clean-Up", :note_photo_file_name => "garden.jpg", :note_photo_content_type => "image/jpeg", :note_photo_file_size => 362431, :note_photo_updated_at => "2013-11-08 16:52:00", :list_id => 5, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => nil, :flag3 => nil, :flag4 => nil, :flag5 => nil, :assigned_user => nil, :note_pos => 2 },
  { :user_id => 1, :crop_id => nil, :text => nil, :title => "Trick or Treat!", :note_photo_file_name => nil, :note_photo_content_type => nil, :note_photo_file_size => nil, :note_photo_updated_at => nil, :list_id => 4, :due_date => nil, :completion => nil, :flag1 => nil, :flag2 => nil, :flag3 => nil, :flag4 => nil, :flag5 => nil, :assigned_user => nil, :note_pos => 0 }
])



Notification.create!([
  { :note_id => 6, :user_id => 1, :due => nil, :text => "Let me know if you need anything is due in 1 day" }
])



User.create!([
  { :name => "Demo", :token => "rXdBvZTyTBt8iLe4ogcC7Q", :password => "password", :zip => 11215, :email => "demo@gmail.com" },
  { :name => "Norma", :token => "aoFJO77byeesKqokdgmvIw", :password => "password", :zip => 11215, :email => "norma@gmail.com" }
])


